### ISSUE TITLE
Network scan not work

### ISSUE THREAD

**Issue by yigido** [perexg/satip-axe#36] opened 2015-11-24 15:13 UTC
When I try a network scan, the first Mux is successfully found, but for the rest I get an error message "scan no data, failed".
I use a digibit r1 with the last beta (I tried also the satip-axe) and tvheadend from git with following configurations:

![1](https://cloud.githubusercontent.com/assets/15986028/11407696/a263a7c8-93b4-11e5-960f-3bd838722e35.jpg)

![2](https://cloud.githubusercontent.com/assets/15986028/11407697/a268cdb6-93b4-11e5-8932-495870014d94.jpg)

![3](https://cloud.githubusercontent.com/assets/15986028/11407695/a26337a2-93b4-11e5-94ed-1961c766c399.jpg)

The digibit shows this errors in the log:
> [686][355717.590][s2i-sock-util][0x13b34b8][listen:ERROR:utils/s2iutilsock.cpp:346][: [error: -1 errno:95 meaning:[Operation not supported]]]
[687][355736.543][s2i-sock-util][0x13b34b8][listen:ERROR:utils/s2iutilsock.cpp:346][: [error: -1 errno:95 meaning:[Operation not supported]]]
[688][355746.550][s2i-sock-util][0x13b34b8][listen:ERROR:utils/s2iutilsock.cpp:346][: [error: -1 errno:95 meaning:[Operation not supported]]]
[689][355756.548][s2i-sock-util][0x13b34b8][listen:ERROR:utils/s2iutilsock.cpp:346][: [error: -1 errno:95 meaning:[Operation not supported]]]
[690][355766.551][s2i-sock-util][0x13b34b8][listen:ERROR:utils/s2iutilsock.cpp:346][: [error: -1 errno:95 meaning:[Operation not supported]]]
[691][355776.550][s2i-sock-util][0x13b34b8][listen:ERROR:utils/s2iutilsock.cpp:346][: [error: -1 errno:95 meaning:[Operation not supported]]]
[692][355786.546][s2i-sock-util][0x13b34b8][listen:ERROR:utils/s2iutilsock.cpp:346][: [error: -1 errno:95 meaning:[Operation not supported]]]

[tvh_log.txt](https://github.com/perexg/satip-axe/files/42816/tvh_log.txt)

**Comment by perexg** [comment] 2015-11-24 15:22
Provide '--trace satip,mpegts' for tvh...

**Comment by yigido** [comment] 2015-11-24 16:00
[tvh_trace_satip_mpegts.txt](https://github.com/perexg/satip-axe/files/42870/tvh_trace_satip_mpegts.txt)

**Comment by perexg** [comment] 2015-11-24 16:26
I'm afraid. There should be [TRACE] lines in the log. See: https://tvheadend.org/projects/tvheadend/wiki/Traces

**Comment by yigido** [comment] 2015-11-24 19:06
Sorry my fault...I have updated the log from the previous post. 
Now seem the first 4muxes working...

**Comment by perexg** [comment] 2015-11-24 19:21
There's an issue on your ethernet network. I see many messages like:

 RTP discontinuity (31519 != 31520)

It means that some UDP packets were lost on the ethernet segment. Usually, the issue is 1Gbit -> 100Mbit conversion or some ethernet switches with small buffers.

If you can try again satip-axe firmware, you may use TCP RTSP connection mode..

**Comment by yigido** [comment] 2015-11-24 19:29
OK i will test it... Thx perexg for help

**Comment by yigido** [comment] 2015-11-25 10:15
So I tested it, but get the same error "scan no data, failed". I use the "RTSP/TCP" option and set "Skip TS packets" to 30. The log shows no discontinuity problems.

[tvh_minisatip.txt](https://github.com/perexg/satip-axe/files/43711/tvh_minisatip.txt)

**Comment by perexg** [comment] 2015-11-25 10:40
OK, I see the problem now. Some PIDs are not subscribed by TVH. Which version do you use ? You've not fetched tags, so iI cannot determine it from logs.

**Comment by yigido** [comment] 2015-11-25 10:54
The git from yesterday, but I don't know the exact version number. Where can I find it?

**Comment by perexg** [comment] 2015-11-25 11:03
<pre>
git pull --tags origin master
git describe
</pre>

**Comment by yigido** [comment] 2015-11-25 11:16
Ok I get the commit "851aebb5aa5f68272cf2ed5af5c83de38e78fb44"

**Comment by perexg** [comment] 2015-11-25 20:01
Could you provide same log with the patch bellow?

<pre>
diff --git a/src/input/mpegts/satip/satip_frontend.c b/src/input/mpegts/satip/satip_frontend.c
index d6d0a68..5dfdedd 100644
--- a/src/input/mpegts/satip/satip_frontend.c
+++ b/src/input/mpegts/satip/satip_frontend.c
@@ -61,6 +61,7 @@ satip_frontend_signal_cb( void *aux )
   signal_status_t        sigstat;
   service_t             *svc;
 
+  tvhtrace("satip", "signal_cb : mmi = %p, sf_tables = %d", mmi, lfe->sf_tables);
   if (mmi == NULL)
     return;
   if (!lfe->sf_tables) {
</pre>

**Comment by yigido** [comment] 2015-11-26 10:33
[tvh_patched.txt](https://github.com/perexg/satip-axe/files/44848/tvh_patched.txt)

**Comment by perexg** [comment] 2015-12-16 09:43
Fixed in v4.1-1233-gc50d70e . Closing.

**Closed by perexg** 2015-12-16 09:43 UTC
